version: '3.7'

services:
  web:
    # Берем Dockerfile из каталога app
    build: ./app
    # Запускаем тестовый сервер
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    # куда будут помещены данные из каталога app
    #    volumes:
    #      - ./app/:/usr/src/app/
    # Открываем порт 8000 внутри и снаружи
    expose:
      - 8000
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    # Образ и версия базы, которую мы будем использовать
    image: postgres:12.0-alpine
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
      
    environment:
      # Учетные данные, которые можно будет переопределить
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db
    expose:
      - 5432
    ports: 
      - 5432:5432
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_volume:
