version: '3.7'

services:
  web:
    # Берем Dockerfile из репозитория
    build: gospodchikovs/e4gospochikov
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 80:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
      
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db
    expose:
      - 5432
    ports: 
      - 5432:5432
  nginx:
    image: nginx
    ports:
      - 81:80
    depends_on:
      - web

volumes:
  postgres_volume:
